pencil_strings = (
  "          XX            ",
  "          XX            ",
  "         XXXX           ",
  "        XX  XX          ",
  "      XX      XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX......XX        ",
  "      XX      XX        ",
  "      XX      XX        ",
  "      XX      XX        ",
  "      XX......XX        ")

