upside_down_arrow_strings = (
  "                        ",
  "                        ",
  "                        ",
  "        XX              ",
  "       XXXX             ",
  "      XX..XX            ",
  "      XX..XX            ",
  "     XX..XX             ",
  "XX   XX..XX             ",
  "XXXX XX..XX             ",
  "XX.XXX..XX              ",
  "XX......XXXXX           ",
  "XX........XXX           ",
  "XX........XX            ",
  "XX.......XX             ",
  "XX......XX              ",
  "XX.....XX               ",
  "XX....XX                ",
  "XX...XX                 ",
  "XX..XX                  ",
  "XX.XX                   ",
  "XXXX                    ",
  "XXX                     ",
  "XX                      ")
